# Change these first
owner: Suiattle # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: City of Seattle Official Website
    url: https://www.seattle.gov
    expectedStatusCodes:
      - 200
      - 201
    headers:
      - "User-Agent: uptime/monitor"
  - name: Seattle Services Portal
    url: https://services.seattle.gov/portal/
  - name: Seattle Services Portal Help Center
    url: https://seattlegov.zendesk.com/hc/
  #- name: SFD Permit and Certification Fees
  #  url: https://web7.seattle.gov/sfd/permits/
  - name: Permit and Property Records Search
    url: https://web.seattle.gov/dpd/edms/
  - name: Permit & Site History Research Tool 
    url: https://maps.seattle.gov/sdcipermithistory/
  - name: Shaping Seattle Maps
    url: https://web.seattle.gov/sdci/ShapingSeattle/
  - name: City of Seattle Vehicle Safety Inspection Database 
    url: https://web6.seattle.gov/FAS/Vsid
  - name: Seattle Animal Shelter Online Licensing
    url: https://onlinelicensing.petpoint.com/OnlineLicensing/
  #- name: Seattle Building & Energy Portal
  #  url: https://buildingenergy.seattle.gov/portal/login
  #- name: Seattle Energy Benchmarking Map
  #  url: https://buildingenergy.seattle.gov/map
  - name: Seattle Municipal Court Payments
    url: https://secure8.i-doxs.net/SeattleSMC/
  - name: Seattle Public Utilities Side Sewer Cards and Maps
    url: https://maps.seattle.gov/sidesewercardviewer/
  - name: Seattle Utilities ePortal
    url: https://myutilities.seattle.gov/eportal/
  - name: Seattle Utility Services One-time Payment
    url: https://utilities-self-service.ebill.seattle.gov/SeattleUtilities/OneTimeAdd.aspx
  #- name: Test Broken Site
  #  url: https://invalid.invalid.invalid
  #- name: IPv6 test
  #  url: services.seattle.gov
  #  port: 443
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  # introTitle: "**Uptime** is an open-source uptime monitor."
  # introMessage: This status page is built using GitHub Actions, Issues, and Pages.
  status-website:
  theme: ocean
  content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /uptime
   # - title: GitHub
   #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
